/*
 * Copyright (C) 2026 Thijs Eilander
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * libFuzzer harness for ngx_http_zstd_dcz_decode_digest().
 *
 * Why this target: it parses the attacker-controlled Available-Dictionary
 * request header -- an RFC 8941 byte-sequence gate (colon framing, a
 * 44-character length ceiling) followed by ngx_decode_base64() and a
 * fixed-32-byte destination buffer. That is exactly the bug class
 * coverage-guided fuzzing finds and the Perl suite (ci/t/03-dcz.t) does
 * not: off-by-one framing, a base64 length that rounds unexpectedly, or
 * a decoded length other than 32 landing past the destination buffer.
 *
 * The real function lives in ../../src/ngx_http_zstd_filter_module.c and
 * depends on the nginx tree only through ngx_str_t/ngx_int_t/NGX_OK/
 * NGX_DECLINED and ngx_decode_base64() -- none of ngx_http_request_t. It
 * was extracted out of ngx_http_zstd_dcz_negotiate() specifically so it
 * could be fuzzed in isolation; see the extraction comment on the
 * function itself. ci/fuzz/extract_dcz.sh slices its verbatim body into
 * generated_dcz.inc at build time, so this always fuzzes the SHIPPED
 * code with no copy drift. ngx_shim.h provides the tiny nginx surface it
 * needs (ngx_decode_base64() included) with faithful upstream semantics.
 *
 * Build (see fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_dcz.c -o fuzz_dcz
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim.h"

/* Generated by ci/fuzz/extract_dcz.sh from
 * ../../src/ngx_http_zstd_filter_module.c. Contains the verbatim body of
 * ngx_http_zstd_dcz_decode_digest(). */
#include "generated_dcz.inc"


int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /*
     * No trailing NUL: ngx_http_zstd_dcz_decode_digest() and everything
     * it calls are fully length-bounded on raw.len, so ASAN turns any
     * read at or past that length into an immediate heap-buffer-overflow
     * failure -- the same discipline fuzz_accept_encoding.c uses.
     */
    size_t  alloc = size ? size : 1;
    u_char *buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }

    if (size) {
        memcpy(buf, data, size);
    }

    ngx_str_t raw;
    raw.data = buf;
    raw.len  = size;

    /*
     * Sized to NGX_HTTP_ZSTD_DCZ_DECODE_BUF_LEN (48), matching the real
     * caller's buffer -- NOT NGX_HTTP_ZSTD_SHA256_DIGEST_LEN (32). An
     * unpadded 44-character byte-sequence decodes to 33 bytes, one past
     * a tight 32-byte buffer, before the post-decode length check runs;
     * ASAN on a 32-byte buffer here would flag that as a harness bug
     * instead of exercising the real function's documented contract.
     * Poisoned so a decode path that writes fewer than
     * NGX_HTTP_ZSTD_SHA256_DIGEST_LEN bytes on a claimed-NGX_OK return
     * (a contract violation) leaves a visible non-zero tail rather than
     * silently reading back a zero-initialized buffer.
     */
    u_char out[NGX_HTTP_ZSTD_DCZ_DECODE_BUF_LEN];
    memset(out, 0xA5, sizeof(out));

    ngx_int_t rc = ngx_http_zstd_dcz_decode_digest(raw, out);

    /*
     * Result must be one of the three documented sentinels: NGX_OK,
     * NGX_DECLINED (malformed byte-sequence framing, rejected before
     * decoding) or NGX_ERROR (well-formed framing, payload is not a
     * 32-byte base64 value). The caller distinguishes the two failure
     * values only to select a diagnostic; both are equally fail-closed.
     */
    if (rc != NGX_OK && rc != NGX_DECLINED && rc != NGX_ERROR) {
        __builtin_trap();
    }

    free(buf);
    return 0;
}
