#!/bin/bash
# Unit fixture for ngx_http_zstd_ceil_log2() (grind-g6-nits owed control).
# The function is `static` inside ngx_http_zstd_filter_module.c, so this
# extracts it verbatim by line range (same technique already used by the
# repo's Accept-Encoding parser fuzz harness) and compiles it standalone
# against a linear-reference oracle in test_ceil_log2_unit.c. No nginx
# tree, no zstd needed — pure C, self-contained.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels since the ci/ move.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-ceil-log2-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

# Locate the function by its exact signature line, then its opening and
# closing braces, so the extraction survives unrelated edits elsewhere in
# the file but fails loudly (grep -c check below) if the function itself
# is renamed or removed.
START_LINE="$(grep -n '^static ngx_inline ngx_uint_t$' "$SRC" | head -1 | cut -d: -f1)"
if [ -z "$START_LINE" ]; then
	echo "FAIL: could not locate ngx_http_zstd_ceil_log2() start in $SRC" >&2
	exit 1
fi

SIG_LINE=$((START_LINE + 1))
if ! sed -n "${SIG_LINE}p" "$SRC" | grep -q 'ngx_http_zstd_ceil_log2(size_t x)'; then
	echo "FAIL: line $SIG_LINE in $SRC is not ngx_http_zstd_ceil_log2's signature" >&2
	exit 1
fi

# First "^}" at column 0 after START_LINE closes the function.
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
END_LINE=$((START_LINE + REL_END - 1))

mkdir -p "$OUT"
{
	echo "/* Generated by test_ceil_log2_unit.sh — verbatim extraction of"
	echo " * ngx_http_zstd_ceil_log2() from $SRC lines ${START_LINE}-${END_LINE}."
	echo " * Do not edit; re-run the script to regenerate. */"
	sed -n "${START_LINE},${END_LINE}p" "$SRC"
} >"$OUT/generated_ceil_log2.inc"

# Sanity: the extraction must actually contain the function body markers,
# or a source reflow silently produced an empty/garbage .inc.
if ! grep -q 'ngx_http_zstd_ceil_log2(size_t x)' "$OUT/generated_ceil_log2.inc"; then
	echo "FAIL: extracted fragment does not contain the function signature" >&2
	cat "$OUT/generated_ceil_log2.inc" >&2
	exit 1
fi
if ! grep -q '__builtin_clzll' "$OUT/generated_ceil_log2.inc"; then
	echo "FAIL: extracted fragment missing the GCC/Clang branch — extraction range wrong" >&2
	exit 1
fi

cp ci/tools/test_ceil_log2_unit.c "$OUT/test_ceil_log2_unit.c"

"$CC" -Wall -Wextra -Werror -O2 -I"$OUT" \
	-o "$OUT/ceil_log2_unit" "$OUT/test_ceil_log2_unit.c"
"$OUT/ceil_log2_unit"

# C89 has neither `unsigned long long` nor C99's mixed declarations.  This
# strict fixture therefore selects the portable fallback, executes its power-
# of-two boundaries, and makes either construct leaking into that path a hard
# compile failure.
cat >"$OUT/test_ceil_log2_c89.c" <<'EOF'
#include <stddef.h>

typedef unsigned long ngx_uint_t;
#define ngx_inline __inline

#include "generated_ceil_log2.inc"

int
main(void)
{
    return ngx_http_zstd_ceil_log2(1024) != 10
           || ngx_http_zstd_ceil_log2(1025) != 11
           || ngx_http_zstd_ceil_log2(4096) != 12
           || ngx_http_zstd_ceil_log2(4097) != 13
           || ngx_http_zstd_ceil_log2((size_t) 1 << 23) != 23;
}
EOF

"$CC" -std=c89 -pedantic-errors -Wall -Wextra -Werror -O2 -I"$OUT" \
	-o "$OUT/ceil_log2_c89" "$OUT/test_ceil_log2_c89.c"
"$OUT/ceil_log2_c89"

echo "OK: ceil_log2 unit fixture (extracted from current $SRC)"
