#!/bin/bash
# Copyright (C) 2026 Thijs Eilander
# SPDX-License-Identifier: BSD-2-Clause
#
# Unit fixture for ngx_http_zstd_pledge_to_bound_input() -- the guard that
# decides whether an upstream-declared off_t body length may be narrowed to
# size_t and handed to ZSTD_compressBound() to size the FIRST output buffer.
#
# The whole defect this closes lives in a width relationship
# (sizeof(off_t) > sizeof(size_t)) that DOES NOT EXIST on the LP64 hosts CI
# runs on. A test that only ran natively would pass on a truncating
# implementation, so this script compiles the fixture TWICE:
#
#   1. natively (LP64 here): proves the 64-bit behaviour is unchanged and
#      that the fast path still accepts ordinary lengths;
#   2. -m32 -D_FILE_OFFSET_BITS=64: the ILP32-with-large-file-support shape,
#      32-bit size_t under a 64-bit off_t. This is the ONLY pass that
#      reaches the SIZE_MAX-overflow branch, i.e. the only one that can
#      observe the truncation. It is not optional coverage.
#
# The function is extracted VERBATIM by line range from src/ rather than
# re-typed, so a future edit to the production arithmetic cannot leave a
# hand-copied duplicate here passing forever.
#
# REQUIRE_M32: unset/"0"/""/false/no/off (case insensitive) keeps the
# default local-dev behaviour -- SKIP with exit 0 when no -m32 toolchain is
# present. Any other value (1/true/yes/on, case insensitive, or anything
# else non-empty) makes a missing -m32 toolchain a hard FAILURE instead.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-pledge-bound-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT
mkdir -p "$OUT"

SIG="$(grep -n '^ngx_http_zstd_pledge_to_bound_input(off_t pledged_size' \
       "$SRC" | head -1 | cut -d: -f1)"
if [ -z "$SIG" ]; then
    echo "FAIL: could not locate ngx_http_zstd_pledge_to_bound_input() in $SRC" >&2
    exit 1
fi

# Signature line is preceded by the storage-class/return-type line.
START=$((SIG - 1))
REL_END="$(tail -n "+${START}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
if [ -z "$REL_END" ]; then
    echo "FAIL: could not find the end of ngx_http_zstd_pledge_to_bound_input()" >&2
    exit 1
fi
END=$((START + REL_END - 1))

{
    echo "/* Generated by test_pledge_bound_input_unit.sh -- verbatim"
    echo " * extraction from $SRC lines ${START}-${END}."
    echo " * Do not edit; re-run the script to regenerate. */"
    sed -n "${START},${END}p" "$SRC"
} > "$OUT/generated_pledge_bound_input.inc"

# Sanity: a source reflow or a regression to a bare cast must fail loudly
# here, not silently produce an .inc that still compiles and "passes".
for marker in 'ngx_http_zstd_pledge_to_bound_input(off_t pledged_size' \
              'sizeof(off_t) > sizeof(size_t)' \
              'SIZE_MAX' \
              'ZSTD_MAX_INPUT_SIZE'; do
    if ! grep -q "$marker" "$OUT/generated_pledge_bound_input.inc"; then
        echo "FAIL: extracted fragment is missing \"$marker\" --" \
             "extraction range wrong, or the full-width guard regressed" >&2
        cat "$OUT/generated_pledge_bound_input.inc" >&2
        exit 1
    fi
done

cp ci/tools/test_pledge_bound_input_unit.c "$OUT/"

# --- native pass ---------------------------------------------------------
"$CC" -Wall -Wextra -Werror -O2 -I"$OUT" \
    -o "$OUT/pledge_bound_unit" "$OUT/test_pledge_bound_input_unit.c"
"$OUT/pledge_bound_unit"
echo "OK: pledged-length bound guard (native, extracted from current $SRC)"

# --- ILP32 + LFS pass ----------------------------------------------------
require_m32="${REQUIRE_M32:-0}"
case "${require_m32,,}" in
    0 | "" | false | no | off) require_m32_set=0 ;;
    *) require_m32_set=1 ;;
esac

if "$CC" -m32 -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Werror -O2 -I"$OUT" \
    -o "$OUT/pledge_bound_unit_ilp32" \
    "$OUT/test_pledge_bound_input_unit.c" >/dev/null 2>&1
then
    "$OUT/pledge_bound_unit_ilp32"
    echo "OK: pledged-length bound guard (ILP32 + LFS, off_t wider than size_t)"
elif [ "$require_m32_set" = "1" ]; then
    echo "FAIL: no 32-bit toolchain available and REQUIRE_M32 is set;" \
         "the ILP32/LFS pass -- the only one that can observe the truncation" \
         "-- cannot run" >&2
    exit 1
else
    echo "SKIP: no 32-bit toolchain available; ILP32/LFS pass not run" >&2
fi
