#!/bin/bash
# Unit fixture for ngx_http_zstd_static_pread().
#
# The helper is `static` inside ngx_http_zstd_static_module.c, so this
# extracts it verbatim by line range (the same technique as
# test_read_dict_file_unit.sh, whose loop this one is deliberately shaped
# after) and compiles it standalone against a scripted pread(2) stub in
# test_static_pread_unit.c. No nginx tree, no zstd needed — pure C.
#
# Extraction, not duplication: a hand-copied body would drift from the
# shipped code and keep passing while the real loop regressed.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_static_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-static-pread-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

# Locate the definition by its signature line (the `static ssize_t`
# return type sits on the line above it, as in this file's house style),
# so the extraction survives unrelated edits but fails loudly if the
# function is renamed or its parameter list changes shape.
SIG_LINE="$(grep -n '^ngx_http_zstd_static_pread(ngx_fd_t fd, u_char \*buf, size_t size,$' "$SRC" | head -1 | cut -d: -f1)"
if [ -z "$SIG_LINE" ]; then
    echo "FAIL: could not locate ngx_http_zstd_static_pread()'s definition in $SRC" >&2
    exit 1
fi

START_LINE=$((SIG_LINE - 1))
if ! sed -n "${START_LINE}p" "$SRC" | grep -q '^static ssize_t$'; then
    echo "FAIL: line $START_LINE in $SRC is not the expected 'static ssize_t' return-type line" >&2
    exit 1
fi

# First "^}" at column 0 after START_LINE closes the function.
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
END_LINE=$((START_LINE + REL_END - 1))

mkdir -p "$OUT"
{
    echo "/* Generated by test_static_pread_unit.sh — verbatim extraction of"
    echo " * ngx_http_zstd_static_pread() from $SRC lines $START_LINE-$END_LINE."
    echo " * Do not edit; regenerate by running the script. */"
    sed -n "${START_LINE},${END_LINE}p" "$SRC"
} > "$OUT/generated_static_pread.inc"

# Non-vacuity: the extraction must actually contain the retry loop AND the
# alignment round-down. An empty or mis-ranged .inc would otherwise compile
# to nothing and "pass"; an .inc that captured only the Win32 arm would
# compile and pass every buffered case while testing none of the POSIX
# behaviour this fixture exists for.
if [ "$(grep -c 'pread' "$OUT/generated_static_pread.inc")" -lt 1 ]; then
    echo "FAIL: extracted .inc contains no pread call — extraction range is wrong" >&2
    sed -n '1,20p' "$OUT/generated_static_pread.inc" >&2
    exit 1
fi
if [ "$(grep -c 'NGX_EINTR' "$OUT/generated_static_pread.inc")" -lt 1 ]; then
    echo "FAIL: extracted .inc has no NGX_EINTR retry — extraction range is wrong" >&2
    exit 1
fi

$CC -std=gnu99 -Wall -Wextra -Werror -O1 \
    -I ci/tools -I "$OUT" \
    -o "$OUT/test_static_pread_unit" \
    ci/tools/test_static_pread_unit.c

"$OUT/test_static_pread_unit"
