#!/bin/bash
# Unit fixture for ngx_http_zstd_estimate_cctx_memory().
#
# This is a CONFIG-TIME function (takes ngx_conf_t *cf, runs during
# "nginx -t"), not a per-request path, so the HTTP fault-injection probe
# endpoint cannot reach it at all -- there is no request in flight for it
# to poison. A direct unit-test harness is the only way to force each of
# its six early-return error exits and observe whether ZSTD_freeCCtxParams()
# actually ran on that exit.
#
# Extraction, not duplication: the function is `static` inside
# ngx_http_zstd_filter_module.c, so this extracts it verbatim by line range
# (the same technique as test_read_dict_file_unit.sh and
# test_cctx_profile_pack.sh) along with the three NGX_HTTP_ZSTD_LDM_* macros
# it references, and compiles it standalone in test_freecctxparams_unit.c
# against scripted ZSTD_* fakes. A hand-copied duplicate of the six exits
# would drift from the shipped code and keep passing while a real one
# regressed to leaking.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-freecctxparams-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT
mkdir -p "$OUT"

# --- the three LDM layout #defines the function references --------------
# Extracted, never re-typed: NGX_HTTP_ZSTD_LDM_WINDOWLOG feeds directly into
# the divisor-derivation arithmetic under test.
DEF_START="$(grep -n '^#define NGX_HTTP_ZSTD_LDM_WINDOWLOG' "$SRC" \
             | head -1 | cut -d: -f1 || true)"
if [ -z "$DEF_START" ]; then
    echo "FAIL: could not locate NGX_HTTP_ZSTD_LDM_WINDOWLOG in $SRC" >&2
    exit 1
fi
DEF_END="$(grep -n '^#define NGX_HTTP_ZSTD_LDM_BUCKETSIZELOG' "$SRC" \
           | head -1 | cut -d: -f1 || true)"
if [ -z "$DEF_END" ]; then
    echo "FAIL: could not locate NGX_HTTP_ZSTD_LDM_BUCKETSIZELOG in $SRC" >&2
    exit 1
fi

# --- the function itself -------------------------------------------------
# Locate by its signature line (the "static char *" return type sits on the
# line above it, as in this file's house style), so extraction survives
# unrelated edits but fails loudly if the function is renamed or removed.
SIG_LINE="$(grep -n '^ngx_http_zstd_estimate_cctx_memory(ngx_conf_t \*cf,$' "$SRC" \
            | head -1 | cut -d: -f1 || true)"
if [ -z "$SIG_LINE" ]; then
    echo "FAIL: could not locate ngx_http_zstd_estimate_cctx_memory()'s definition in $SRC" >&2
    exit 1
fi

FUNC_START=$((SIG_LINE - 1))
if ! sed -n "${FUNC_START}p" "$SRC" | grep -q '^static char \*$'; then
    echo "FAIL: line $FUNC_START in $SRC is not the expected 'static char *' return-type line" >&2
    exit 1
fi

REL_END="$(tail -n "+${FUNC_START}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1 || true)"
if [ -z "$REL_END" ]; then
    echo "FAIL: could not find the closing '}' for ngx_http_zstd_estimate_cctx_memory() in $SRC" >&2
    exit 1
fi
FUNC_END=$((FUNC_START + REL_END - 1))

{
    echo "/* Generated by test_freecctxparams_unit.sh — verbatim extraction of"
    echo " * NGX_HTTP_ZSTD_LDM_* from $SRC lines $DEF_START-$DEF_END and"
    echo " * ngx_http_zstd_estimate_cctx_memory() from lines $FUNC_START-$FUNC_END."
    echo " * Do not edit; regenerate by running the script. */"
    sed -n "${DEF_START},${DEF_END}p" "$SRC"
    echo
    sed -n "${FUNC_START},${FUNC_END}p" "$SRC"
} > "$OUT/generated_estimate_cctx_memory.inc"

# Non-vacuity: the extraction must actually contain all six error-exit frees
# plus the one success-path free, i.e. seven ZSTD_freeCCtxParams call sites.
# A mis-ranged .inc would compile to nothing (or a truncated function) and
# silently "pass" every scenario since none of the fakes would ever fire.
FREE_CALLS="$(grep -c 'ZSTD_freeCCtxParams(cp)' "$OUT/generated_estimate_cctx_memory.inc" || true)"
if [ "$FREE_CALLS" -ne 7 ]; then
    echo "FAIL: extracted .inc contains $FREE_CALLS ZSTD_freeCCtxParams(cp) call(s), expected 7 (six error exits + one success exit) — extraction range is wrong" >&2
    exit 1
fi

$CC -std=gnu99 -Wall -Wextra -Werror -O1 \
    -DZSTD_STATIC_LINKING_ONLY \
    -I ci/tools -I "$OUT" \
    -o "$OUT/test_freecctxparams_unit" \
    ci/tools/test_freecctxparams_unit.c

"$OUT/test_freecctxparams_unit"
