#!/bin/bash
# Unit fixture for ngx_http_zstd_static_should_bypass() (A33-F3).
#
# The predicate is `static` inside ngx_http_zstd_static_module.c, so this
# extracts it verbatim by line range (the same technique as
# test_static_pread_unit.sh, whose structure this one follows) and compiles
# it standalone against stubbed nginx types. No nginx tree, no zstd needed.
#
# Extraction, not duplication: a hand-copied body would drift from the
# shipped code and keep passing while the real predicate regressed.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_static_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-should-bypass-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

# Locate the definition by its signature line, so the extraction survives
# unrelated edits but fails loudly if the function is renamed or its
# parameter list changes shape.
SIG_LINE="$(grep -n '^ngx_http_zstd_static_should_bypass(ngx_http_request_t \*r)$' "$SRC" | head -1 | cut -d: -f1)"
if [ -z "$SIG_LINE" ]; then
    echo "FAIL: could not locate ngx_http_zstd_static_should_bypass() in $SRC" >&2
    exit 1
fi

START_LINE=$((SIG_LINE - 1))
if ! sed -n "${START_LINE}p" "$SRC" | grep -q '^static ngx_uint_t$'; then
    echo "FAIL: line $START_LINE in $SRC is not the expected 'static ngx_uint_t' return-type line" >&2
    exit 1
fi

# First "^}" at column 0 after START_LINE closes the function.
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
END_LINE=$((START_LINE + REL_END - 1))

mkdir -p "$OUT"
{
    echo "/* Generated by test_static_should_bypass_unit.sh -- verbatim"
    echo " * extraction of ngx_http_zstd_static_should_bypass() from $SRC"
    echo " * lines $START_LINE-$END_LINE. Do not edit; regenerate by running"
    echo " * the script. */"
    sed -n "${START_LINE},${END_LINE}p" "$SRC"
} >"$OUT/generated_static_should_bypass.inc"

# Non-vacuity: the extraction must actually contain the header comparison
# AND the coding-weight call. An empty or mis-ranged .inc would otherwise
# compile to nothing and "pass".
if ! grep -q 'Available-Dictionary' "$OUT/generated_static_should_bypass.inc"; then
    echo "FAIL: extracted .inc has no Available-Dictionary comparison -- extraction range is wrong" >&2
    sed -n '1,20p' "$OUT/generated_static_should_bypass.inc" >&2
    exit 1
fi
if ! grep -q 'ngx_http_zstd_request_coding_weight' "$OUT/generated_static_should_bypass.inc"; then
    echo "FAIL: extracted .inc has no coding-weight call -- extraction range is wrong" >&2
    sed -n '1,20p' "$OUT/generated_static_should_bypass.inc" >&2
    exit 1
fi

"$CC" -std=c99 -D_GNU_SOURCE -Wall -Wextra -O1 \
    -I"$OUT" \
    -o "$OUT/test_static_should_bypass_unit" \
    ci/tools/test_static_should_bypass_unit.c

"$OUT/test_static_should_bypass_unit"
