#!/bin/bash
# Differential fixture for ngx_http_zstd_dcz_dict_lookup() -- A33-P4.
#
# ngx_http_zstd_dcz_dict_lookup() and its sort comparator
# ngx_http_zstd_dcz_dict_cmp() are `static` inside
# src/ngx_http_zstd_filter_module.c, so this extracts them verbatim by
# line range (same technique already used by
# ci/tools/test_ceil_log2_unit.sh and the Accept-Encoding parser fuzz
# harness) and compiles them standalone against a reference brute-force
# linear-scan oracle in test_dcz_dict_lookup_unit.c. No nginx tree, no
# zstd needed -- pure C, self-contained.
#
# This proves the negotiation lookup (which switches from a linear
# ngx_memcmp scan to a binary search once the configured dictionary
# count exceeds NGX_HTTP_ZSTD_DCZ_BSEARCH_THRESHOLD) returns identical
# verdicts to a naive linear scan for every case: sizes straddling the
# threshold, a hit on the first/middle/last element, and misses
# including keys that sort before the first and after the last entry.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels since the ci/ move.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-dcz-lookup-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

extract_by_signature() {
    # $1 = signature-line grep pattern (the K&R-style function-name
    # line, one line below the return-type line); $2 = output file;
    # $3 = a substring the extraction must contain (extraction-range
    # sanity check).
    local sig_pattern="$1"
    local outfile="$2"
    local must_contain="$3"

    local sig_line
    sig_line="$(grep -n "$sig_pattern" "$SRC" | head -1 | cut -d: -f1 || true)"
    if [ -z "$sig_line" ]; then
        echo "FAIL: could not locate '$sig_pattern' in $SRC" >&2
        exit 1
    fi

    # The return-type line is directly above the signature line for
    # every function in this file (K&R style: type on its own line).
    local start_line=$((sig_line - 1))

    # First "^}" at column 0 after start_line closes the function (or
    # struct, for the type extraction).
    local rel_end
    rel_end="$(tail -n "+${start_line}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1 || true)"
    if [ -z "$rel_end" ]; then
        echo "FAIL: could not locate the end of '$sig_pattern' in $SRC" >&2
        exit 1
    fi
    local end_line=$((start_line + rel_end - 1))

    {
        echo "/* Generated by test_dcz_dict_lookup_unit.sh -- verbatim"
        echo " * extraction from $SRC lines ${start_line}-${end_line}."
        echo " * Do not edit; re-run the script to regenerate. */"
        sed -n "${start_line},${end_line}p" "$SRC"
        echo
    } >>"$outfile"

    if ! grep -q "$must_contain" "$outfile"; then
        echo "FAIL: extracted fragment ('$sig_pattern') missing '$must_contain' -- extraction range wrong" >&2
        cat "$outfile" >&2
        exit 1
    fi
}

mkdir -p "$OUT"
INC="$OUT/generated_dcz_dict_lookup.inc"
: >"$INC"

# 1) The threshold constant (a single #define line, grabbed directly --
#    not a function, so the signature/brace extractor doesn't apply).
if ! grep -q '^#define NGX_HTTP_ZSTD_DCZ_BSEARCH_THRESHOLD' "$SRC"; then
    echo "FAIL: NGX_HTTP_ZSTD_DCZ_BSEARCH_THRESHOLD not found in $SRC" >&2
    exit 1
fi
grep '^#define NGX_HTTP_ZSTD_DCZ_BSEARCH_THRESHOLD' "$SRC" >>"$INC"
echo >>"$INC"

# 2) NGX_HTTP_ZSTD_SHA256_DIGEST_LEN (needed by the struct/functions
#    below). Lives in ngx_http_zstd_sha256.h, not $SRC.
SHA_HDR="src/ngx_http_zstd_sha256.h"
if ! grep -q '^#define NGX_HTTP_ZSTD_SHA256_DIGEST_LEN' "$SHA_HDR"; then
    echo "FAIL: NGX_HTTP_ZSTD_SHA256_DIGEST_LEN not found in $SHA_HDR" >&2
    exit 1
fi
grep '^#define NGX_HTTP_ZSTD_SHA256_DIGEST_LEN' "$SHA_HDR" >>"$INC"
echo >>"$INC"

# NGX_HTTP_ZSTD_DCZ_HEADER_LEN: the struct's frame_header field sizes
# against it; grab it too so the verbatim struct extraction compiles.
if ! grep -q '^#define NGX_HTTP_ZSTD_DCZ_HEADER_LEN' "$SRC"; then
    echo "FAIL: NGX_HTTP_ZSTD_DCZ_HEADER_LEN not found in $SRC" >&2
    exit 1
fi
grep '^#define NGX_HTTP_ZSTD_DCZ_HEADER_LEN' "$SRC" >>"$INC"
echo >>"$INC"

# 3) The ngx_http_zstd_dcz_dict_t struct (only the fields the lookup
#    touches are needed by the test harness, but extracting the real
#    struct verbatim means a field reorder/rename cannot silently drift
#    the fixture out of sync with the shipped layout).
STRUCT_END="$(grep -n '^} ngx_http_zstd_dcz_dict_t;' "$SRC" | head -1 | cut -d: -f1 || true)"
STRUCT_START="$(head -n "${STRUCT_END:-0}" "$SRC" | grep -n '^typedef struct {$' | tail -1 | cut -d: -f1 || true)"
if [ -z "$STRUCT_START" ] || [ -z "$STRUCT_END" ]; then
    echo "FAIL: could not locate ngx_http_zstd_dcz_dict_t struct bounds in $SRC" >&2
    exit 1
fi
{
    echo "/* Generated: ngx_http_zstd_dcz_dict_t, $SRC lines ${STRUCT_START}-${STRUCT_END}. */"
    sed -n "${STRUCT_START},${STRUCT_END}p" "$SRC"
    echo
} >>"$INC"
if ! grep -q 'ngx_http_zstd_dcz_dict_t;' "$INC"; then
    echo "FAIL: struct extraction missing its typedef name" >&2
    exit 1
fi

# 4) ngx_http_zstd_dcz_dict_cmp() -- the sort comparator.
extract_by_signature '^ngx_http_zstd_dcz_dict_cmp(const void \*one, const void \*two)$' \
    "$INC" 'ngx_http_zstd_dcz_dict_cmp(const void \*one, const void \*two)'

# 5) The production sort wrapper. The fixture calls this rather than
#    sorting its own positive-case array, so removing the merge-time sort
#    cannot leave this test green.
extract_by_signature '^ngx_http_zstd_dcz_dict_sort(ngx_array_t \*dcz_dicts)$' \
    "$INC" 'ngx_qsort'

# 6) ngx_http_zstd_dcz_dict_lookup() -- the function under test.
extract_by_signature '^ngx_http_zstd_dcz_dict_lookup(ngx_array_t \*dcz_dicts,$' \
    "$INC" 'ngx_http_zstd_dcz_dict_lookup'
if ! grep -q 'NGX_HTTP_ZSTD_DCZ_BSEARCH_THRESHOLD' "$INC"; then
    echo "FAIL: lookup extraction missing the threshold branch -- extraction range wrong" >&2
    exit 1
fi

# The wrapper must be wired before pointer inheritance is resolved. This
# distinguishes an owned location array from a child sharing its parent's
# already-sorted array, and makes deleting the production call fail the gate.
SORT_CALL_LINE="$(grep -n 'ngx_http_zstd_dcz_dict_sort(conf->dcz_dicts);' "$SRC" | cut -d: -f1 || true)"
MERGE_LINE="$(grep -n 'ngx_conf_merge_ptr_value(conf->dcz_dicts, prev->dcz_dicts, NULL);' "$SRC" | cut -d: -f1 || true)"
if [ -z "$SORT_CALL_LINE" ] || [ -z "$MERGE_LINE" ] || [ "$SORT_CALL_LINE" -ge "$MERGE_LINE" ]; then
    echo "FAIL: owned dcz dictionary array is not sorted before inheritance" >&2
    exit 1
fi

cp ci/tools/test_dcz_dict_lookup_unit.c "$OUT/test_dcz_dict_lookup_unit.c"

"$CC" -std=c89 -pedantic-errors -Wall -Wextra -Werror -O2 -I"$OUT" \
    -o "$OUT/dcz_dict_lookup_unit" "$OUT/test_dcz_dict_lookup_unit.c"
"$OUT/dcz_dict_lookup_unit"

echo "OK: dcz dict lookup differential fixture (extracted from current $SRC)"
