#!/bin/bash
# Copyright (C) 2026 Thijs Eilander
# SPDX-License-Identifier: BSD-2-Clause
#
# Unit fixture for the body filter's caller-owned input cursor and lazy tail
# copy.  The two shipped helpers are extracted verbatim, then compiled against
# a minimal nginx pool/chain shim.  This makes ownership, ordering and the
# allocation-failure boundary deterministic without needing socket pressure to
# land at one exact event-loop iteration.
set -euo pipefail

cd "$(dirname "$0")/../.."

SRC=src/ngx_http_zstd_filter_module.c
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-input-cursor-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

extract_function() {
    local signature="$1" label="$2" sig start rel end

    sig="$(grep -n "^${signature}" "$SRC" | head -1 | cut -d: -f1)"
    if [ -z "$sig" ]; then
        echo "FAIL: could not locate $label in $SRC" >&2
        exit 1
    fi

    start=$((sig - 1))
    rel="$(tail -n "+${start}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
    end=$((start + rel - 1))
    sed -n "${start},${end}p" "$SRC"
}

{
    echo "/* Generated by test_input_chain_cursor_unit.sh from $SRC. */"
    extract_function 'ngx_http_zstd_filter_copy_input(' copy_input
    echo
    extract_function 'ngx_http_zstd_filter_add_data(' add_data
} >"$OUT/generated_input_cursor.inc"

for marker in ngx_http_zstd_filter_copy_input ngx_http_zstd_filter_add_data \
              'retained = ctx->in != NULL' 'ngx_free_chain(r->pool, cl)'; do
    if ! grep -q "$marker" "$OUT/generated_input_cursor.inc"; then
        echo "FAIL: extracted fragment is missing $marker" >&2
        exit 1
    fi
done

# The body-filter return boundary is part of the contract but deliberately is
# not duplicated in the C shim.  Pin the production wiring: an unconsumed local
# cursor must be copied immediately before the ordinary pause return, and a
# copy failure must enter the existing terminal label.
if ! sed -n '/if (ctx->out == NULL && !flush)/,/return ctx->busy/p' "$SRC" \
    | grep -A4 'ngx_http_zstd_filter_copy_input' \
    | grep -q 'goto failed;'
then
    echo "FAIL: body-filter pause return no longer terminally handles lazy-copy failure" >&2
    exit 1
fi

if ! sed -n '/ngx_http_zstd_filter_compress(r, ctx,/,/);/p' "$SRC" \
    | grep -q 'ctx->in == NULL && in == NULL'
then
    echo "FAIL: compressor terminal decision does not include both input queues" >&2
    exit 1
fi

cp ci/tools/test_input_chain_cursor_unit.c "$OUT/test_input_chain_cursor_unit.c"
"$CC" -std=c99 -O2 -Wall -Wextra -Werror -I"$OUT" \
    -o "$OUT/test_input_chain_cursor_unit" \
    "$OUT/test_input_chain_cursor_unit.c"
timeout 30s "$OUT/test_input_chain_cursor_unit"
