#!/bin/bash
# Unit fixture for the CCtx profile 64-bit key (ngx_http_zstd_profile_pack /
# ngx_http_zstd_profile_unpack).
#
# The row this test exists for demands a COLLISION-FREE, REVERSIBLE key --
# explicitly not a hash. That property is only worth asserting against the
# code that actually ships, so this extracts the packer, the unpacker and
# their layout #defines VERBATIM from ngx_http_zstd_filter_module.c by line
# range (the same technique as test_ceil_log2_unit.sh) and compiles them
# standalone. A hand-copied duplicate of the arithmetic would pass forever
# while production drifted underneath it -- which is the exact failure this
# extraction prevents.
#
# No nginx tree and no libzstd needed: pure C, self-contained.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels since the ci/ move.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-profile-pack-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

mkdir -p "$OUT"

# --- the layout #defines -------------------------------------------------
# Extracted, never re-typed: the widths and the bias ARE the contract under
# test. Redeclaring them here would let the test agree with itself.
DEF_START="$(grep -n '^#define NGX_HTTP_ZSTD_PROFILE_LEVEL_BIAS' "$SRC" \
             | head -1 | cut -d: -f1)"
if [ -z "$DEF_START" ]; then
    echo "FAIL: could not locate NGX_HTTP_ZSTD_PROFILE_LEVEL_BIAS in $SRC" >&2
    exit 1
fi
DEF_END="$(grep -n '^#define NGX_HTTP_ZSTD_PROFILE_INVALID' "$SRC" \
           | head -1 | cut -d: -f1)"
if [ -z "$DEF_END" ]; then
    echo "FAIL: could not locate NGX_HTTP_ZSTD_PROFILE_INVALID in $SRC" >&2
    exit 1
fi

# --- the packer ----------------------------------------------------------
PACK_START="$(grep -n '^ngx_http_zstd_profile_pack(ngx_int_t level' "$SRC" \
              | head -1 | cut -d: -f1)"
if [ -z "$PACK_START" ]; then
    echo "FAIL: could not locate ngx_http_zstd_profile_pack() in $SRC" >&2
    exit 1
fi
PACK_START=$((PACK_START - 1))          # the "static uint64_t" line
REL="$(tail -n "+${PACK_START}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
PACK_END=$((PACK_START + REL - 1))

# --- the unpacker --------------------------------------------------------
UNPACK_START="$(grep -n '^ngx_http_zstd_profile_unpack(uint64_t key' "$SRC" \
                | head -1 | cut -d: -f1)"
if [ -z "$UNPACK_START" ]; then
    echo "FAIL: could not locate ngx_http_zstd_profile_unpack() in $SRC" >&2
    exit 1
fi
UNPACK_START=$((UNPACK_START - 1))      # the "static void" line
REL="$(tail -n "+${UNPACK_START}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
UNPACK_END=$((UNPACK_START + REL - 1))

{
    echo "/* Generated by test_cctx_profile_pack.sh -- verbatim extraction"
    echo " * from $SRC:"
    echo " *   defines  lines ${DEF_START}-${DEF_END}"
    echo " *   pack     lines ${PACK_START}-${PACK_END}"
    echo " *   unpack   lines ${UNPACK_START}-${UNPACK_END}"
    echo " * Do not edit; re-run the script to regenerate. */"
    sed -n "${DEF_START},${DEF_END}p" "$SRC"
    echo
    sed -n "${PACK_START},${PACK_END}p" "$SRC"
    echo
    sed -n "${UNPACK_START},${UNPACK_END}p" "$SRC"
} > "$OUT/generated_profile_pack.inc"

# Sanity: a source reflow must fail loudly here, not produce a garbage .inc
# that still compiles and "passes".
for marker in NGX_HTTP_ZSTD_PROFILE_LEVEL_BIAS \
              NGX_HTTP_ZSTD_PROFILE_INVALID \
              'ngx_http_zstd_profile_pack(ngx_int_t level' \
              'ngx_http_zstd_profile_unpack(uint64_t key'; do
    if ! grep -q "$marker" "$OUT/generated_profile_pack.inc"; then
        echo "FAIL: extracted fragment missing '$marker' -- range wrong" >&2
        cat "$OUT/generated_profile_pack.inc" >&2
        exit 1
    fi
done

cp ci/tools/test_cctx_profile_pack.c "$OUT/test_cctx_profile_pack.c"

"$CC" -Wall -Wextra -Werror -O2 -I"$OUT" \
    -o "$OUT/profile_pack_unit" "$OUT/test_cctx_profile_pack.c"
"$OUT/profile_pack_unit"

echo "OK: CCtx profile pack/unpack unit fixture (extracted from current $SRC)"
