#!/bin/bash
# Unit fixture for the static module's probe-verdict cache.
#
# ngx_http_zstd_static_cached_verdict() and ngx_http_zstd_static_remember(),
# plus the table and the VERDICT_* constants they read, are all `static`
# inside ngx_http_zstd_static_module.c, so this extracts them verbatim by
# line range (the same technique as test_static_pread_unit.sh, whose shape
# this one follows) and compiles them standalone against the minimal type
# surface in test_static_verdict_cache_unit.c. No nginx tree, no zstd, no
# filesystem -- pure C.
#
# Extraction, not duplication: a hand-copied key comparison would drift from
# the shipped one and keep passing while production started ignoring a field.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_static_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-verdict-cache-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

INC="$OUT/generated_verdict_cache.inc"

# --- slice 1: the VERDICT_* constants, the struct and the table ---------
#
# Anchored on the SLOTS #define and closed on the table's high-water counter
# declaration, so an edit that moves either end fails loudly here instead
# of silently extracting a partial or over-wide range.
DECL_START="$(grep -n -m1 '^#define NGX_HTTP_ZSTD_STATIC_VERDICT_CACHE_SLOTS ' \
    "$SRC" | cut -d: -f1 || true)"
DECL_END="$(grep -n -m1 \
    '^static ngx_uint_t  ngx_http_zstd_static_verdict_cache_count;$' \
    "$SRC" | cut -d: -f1 || true)"

if [ -z "$DECL_START" ] || [ -z "$DECL_END" ] || [ "$DECL_END" -le "$DECL_START" ]; then
    echo "FAIL: could not locate the verdict-cache declarations in $SRC" >&2
    exit 1
fi

# --- slice 2 and 3: the two helpers, each by its signature line ---------
extract_fn() {
    # $1 = exact signature line, $2 = expected return-type line above it
    local sig_re="$1" rettype="$2" sig start rel end

    sig="$(grep -n -m1 "$sig_re" "$SRC" | cut -d: -f1 || true)"
    if [ -z "$sig" ]; then
        echo "FAIL: could not locate a definition matching '$sig_re' in $SRC" >&2
        exit 1
    fi

    start=$((sig - 1))
    if ! sed -n "${start}p" "$SRC" | grep -q "^${rettype}\$"; then
        echo "FAIL: line $start in $SRC is not the expected '$rettype' line" >&2
        exit 1
    fi

    # First "^}" at column 0 after start closes the function.
    rel="$(awk -v start="$start" \
        'NR >= start && /^}$/ { print NR - start + 1; exit }' "$SRC")"
    if [ -z "$rel" ]; then
        echo "FAIL: could not find the end of '$sig_re' in $SRC" >&2
        exit 1
    fi
    end=$((start + rel - 1))

    sed -n "${start},${end}p" "$SRC"
}

{
    echo "/* Generated by test_static_verdict_cache_unit.sh -- verbatim"
    echo " * extraction from $SRC. Do not edit; regenerate by running the"
    echo " * script. */"
    sed -n "${DECL_START},${DECL_END}p" "$SRC" \
        | grep -v '^#if (NGX_HTTP_ZSTD_STATIC_HAVE_PROBE)$'
    echo
    extract_fn '^ngx_http_zstd_static_cached_verdict(ngx_str_t \*path, ngx_open_file_info_t \*of,$' \
        'static ngx_uint_t'
    echo
    extract_fn '^ngx_http_zstd_static_remember(ngx_str_t \*path, ngx_open_file_info_t \*of,$' \
        'static void'
} >"$INC"

# Non-vacuity. An empty or mis-ranged .inc would compile to nothing and
# "pass"; each grep below names one thing the fixture cannot test if it is
# missing from the slice.
for needle in \
    'NGX_HTTP_ZSTD_STATIC_VERDICT_GOOD' \
    'NGX_HTTP_ZSTD_STATIC_VERDICT_CACHE_SLOTS' \
    'entry->uniq == of->uniq' \
    'good_valid == 0' \
    'entry->checked' \
    'entry->valid = verdict' \
    'ngx_http_zstd_static_verdict_cache_count' \
    'ngx_http_zstd_static_verdict_cache_next = 0'; do
    if ! grep -q "$needle" "$INC"; then
        echo "FAIL: extracted .inc is missing '$needle' -- extraction range is wrong" >&2
        sed -n '1,20p' "$INC" >&2
        exit 1
    fi
done

compile_fixture() {
    local output=$1

    shift
    # CC may deliberately include a wrapper or compiler flags.
    # shellcheck disable=SC2086
    $CC -std=gnu99 -Wall -Wextra -Werror -O1 \
        -I ci/tools -I "$OUT" "$@" \
        -o "$output" ci/tools/test_static_verdict_cache_unit.c
}

compile_fixture "$OUT/test_static_verdict_cache_unit"
"$OUT/test_static_verdict_cache_unit"

# An expired matching entry must be retired before lookup continues.  Restore
# the old immediate return and require the recovery assertions to catch the
# stale entry masking the freshly inserted duplicate behind it.
awk '
    /entry->valid = NGX_HTTP_ZSTD_STATIC_VERDICT_NONE;/ {
        if (getline next_line <= 0 || next_line !~ /^[[:space:]]*continue;/) {
            exit 2
        }
        print "                return NGX_HTTP_ZSTD_STATIC_VERDICT_NONE;"
        next
    }
    { print }
' "$INC" >"$OUT/generated_verdict_cache_expired_mutant.inc"
compile_fixture "$OUT/test_static_verdict_cache_expired_mutant" \
    -DTEST_EXPIRED_ENTRY_MUTANT
if "$OUT/test_static_verdict_cache_expired_mutant" \
    >"$OUT/expired-mutant.log" 2>&1; then
    echo "FAIL: stale-entry return mutant passed the recovery fixture" >&2
    exit 1
fi
if ! grep -Fq 'FAIL a fresh verdict is visible after an expired duplicate' \
    "$OUT/expired-mutant.log"; then
    echo "FAIL: stale-entry mutant failed for an unrelated reason" >&2
    cat "$OUT/expired-mutant.log" >&2
    exit 1
fi

# Removing only the byte comparison leaves the length guard intact.  The
# equal-length/different-path arm must still reject that weakened cache key.
sed 's/            && ngx_memcmp(entry->path, path->data, path->len) == 0)/            )/' \
    "$INC" >"$OUT/generated_verdict_cache_path_mutant.inc"
if grep -Fq 'ngx_memcmp(entry->path' \
    "$OUT/generated_verdict_cache_path_mutant.inc"; then
    echo "FAIL: path-comparison mutation did not apply" >&2
    exit 1
fi
compile_fixture "$OUT/test_static_verdict_cache_path_mutant" \
    -DTEST_PATH_COMPARE_MUTANT
if "$OUT/test_static_verdict_cache_path_mutant" \
    >"$OUT/path-mutant.log" 2>&1; then
    echo "FAIL: path-comparison mutant passed the equal-length fixture" >&2
    exit 1
fi
if ! grep -Fq \
    "FAIL an equal-length different path does not reuse a GOOD verdict" \
    "$OUT/path-mutant.log"; then
    echo "FAIL: path-comparison mutant failed for an unrelated reason" >&2
    cat "$OUT/path-mutant.log" >&2
    exit 1
fi

echo "OK: verdict-cache mutation controls"
