#!/bin/bash
# Copyright (C) 2026 Thijs Eilander
# SPDX-License-Identifier: BSD-2-Clause
#
# Unit fixture for ngx_http_zstd_max_length_exceeded() -- the
# length-independent zstd_max_length cap checked per iteration of the
# streaming body filter.
#
# The predicate compares ctx->bytes_in (uint64_t) against zlcf->max_length
# (ssize_t). A signed-cast form of this comparison used to read
# `(off_t) bytes_in > (off_t) max_length`: that cast only loses bits when
# off_t itself is narrower than the accumulator, which needs a genuine
# 32-bit off_t (glibc's legacy default with no _FILE_OFFSET_BITS override).
# A native 64-bit host build has an 8-byte off_t regardless, and so does an
# ILP32+LFS build (-m32 -D_FILE_OFFSET_BITS=64): neither can distinguish the
# signed-cast form from the fixed unsigned form, both give the same answer.
# Plain -m32 with NO _FILE_OFFSET_BITS override is the one shape that
# reproduces the truncation, so it is not optional coverage; a native or
# ILP32+LFS run alone would let a regression back into the signed-cast form
# pass silently.
#
# The function is extracted VERBATIM by line range and compiled standalone,
# so a hand-copied duplicate of the arithmetic cannot quietly drift from
# production.
#
# No nginx tree and no libzstd needed: pure C, self-contained.
#
# REQUIRE_M32: unset/"0"/""/false/no/off (case insensitive) keeps the
# default local-dev behaviour -- SKIP with exit 0 when no -m32 toolchain is
# present. Any other value (1/true/yes/on, case insensitive, or anything
# else non-empty) makes a missing -m32 toolchain a hard FAILURE instead.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-max-length-cap-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT
mkdir -p "$OUT"

extract() {   # $1 = start line, $2 = label; prints "start end"
    local start="$1" label="$2" rel end
    if [ -z "$start" ]; then
        echo "FAIL: could not locate $label in $SRC" >&2
        exit 1
    fi
    rel="$(tail -n "+${start}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
    end=$((start + rel - 1))
    echo "$start $end"
}

# --- ngx_http_zstd_max_length_exceeded() (the predicate under test) ------
SIG="$(grep -n '^ngx_http_zstd_max_length_exceeded(uint64_t bytes_in' "$SRC" \
       | head -1 | cut -d: -f1)"
if [ -z "$SIG" ]; then
    echo "FAIL: could not locate ngx_http_zstd_max_length_exceeded() in $SRC" >&2
    exit 1
fi
read -r START END < <(extract "$((SIG - 1))" "max_length_exceeded")

{
    echo "/* Generated by test_max_length_cap_unit.sh -- verbatim extraction"
    echo " * from $SRC:"
    echo " *   ngx_http_zstd_max_length_exceeded lines ${START}-${END}"
    echo " * Do not edit; re-run the script to regenerate. */"
    sed -n "${START},${END}p" "$SRC"
} > "$OUT/generated_max_length_cap.inc"

# Sanity: a source reflow must fail loudly here, not produce a garbage .inc
# that still compiles and "passes".
for marker in 'ngx_http_zstd_max_length_exceeded(uint64_t bytes_in' \
              'NGX_CONF_UNSET'; do
    if ! grep -q "$marker" "$OUT/generated_max_length_cap.inc"; then
        echo "FAIL: extracted fragment is missing \"$marker\"" >&2
        cat "$OUT/generated_max_length_cap.inc" >&2
        exit 1
    fi
done

cp ci/tools/test_max_length_cap_unit.c "$OUT/test_max_length_cap_unit.c"

"$CC" -Wall -Wextra -Werror -O2 -I"$OUT" \
    -o "$OUT/max_length_cap_unit" "$OUT/test_max_length_cap_unit.c"
"$OUT/max_length_cap_unit"

echo "OK: max_length cap unit fixture (extracted from current $SRC)"

# 32-bit off_t pass: a plain native build on this (64-bit) host, and even an
# ILP32+LFS build (-m32 -D_FILE_OFFSET_BITS=64), both give off_t 8 bytes --
# casting bytes_in through it never truncates there, so the historical
# `(off_t) bytes_in > (off_t) max_length` form cannot be distinguished from
# the fixed unsigned comparison on either. The defect needs off_t ITSELF
# narrow: plain -m32 with NO _FILE_OFFSET_BITS override gives a 4-byte
# off_t (glibc's legacy 32-bit off_t), which is what this cap's comment
# describes and what reproduces the cast losing bits. Not optional
# coverage; skipped (not failed) when the runner has no 32-bit toolchain
# at all -- UNLESS REQUIRE_M32 is set to a truthy value (1/true/yes/on,
# case insensitive; anything else non-empty and not "0" also counts as
# set), in which case a missing toolchain is a hard failure rather than a
# silent skip (set in CI so a runner image that drops multilib loses this
# lens loudly, not quietly).
require_m32="${REQUIRE_M32:-0}"
case "${require_m32,,}" in
    0 | "" | false | no | off) require_m32_set=0 ;;
    *) require_m32_set=1 ;;
esac
if "$CC" -m32 -x c -o /dev/null - <<<'int main(void){return 0;}' \
    >/dev/null 2>&1
then
    "$CC" -m32 -Wall -Wextra -Werror -O2 -I"$OUT" \
        -o "$OUT/max_length_cap_unit_32off" "$OUT/test_max_length_cap_unit.c"
    "$OUT/max_length_cap_unit_32off"
    echo "OK: max_length cap unit fixture (32-bit off_t, bytes_in > INT32_MAX)"
elif [ "$require_m32_set" = "1" ]; then
    echo "FAIL: no -m32 toolchain available and REQUIRE_M32 is set; 32-bit off_t pass cannot run" >&2
    exit 1
else
    echo "SKIP: no -m32 toolchain available; 32-bit off_t pass not run" >&2
fi
