#!/bin/bash
# Unit fixture for ngx_http_zstd_static_dio_err_should_log() (A33-F4(b) log
# rate limit for the directio hard-error probe arm).
#
# The function is `static` inside src/ngx_http_zstd_static_module.c, so this
# extracts it verbatim by line range (same technique already used by
# ci/tools/test_ceil_log2_unit.sh for ngx_http_zstd_ceil_log2()) and compiles
# it standalone against a fake, test-controlled ngx_time() clock. No nginx
# tree, no zstd, no filesystem — pure C over a tiny counter.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: two levels since the ci/ move.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_static_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-dio-ratelimit-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

# Locate the function by its exact signature line, then its opening and
# closing braces, so the extraction survives unrelated edits elsewhere in
# the file but fails loudly if the function itself is renamed or removed.
START_LINE="$(grep -n '^static ngx_uint_t$' "$SRC" | head -1 | cut -d: -f1)"
if [ -z "$START_LINE" ]; then
    echo "FAIL: could not locate ngx_http_zstd_static_dio_err_should_log() start in $SRC" >&2
    exit 1
fi

SIG_LINE=$((START_LINE + 1))
if ! sed -n "${SIG_LINE}p" "$SRC" \
    | grep -q 'ngx_http_zstd_static_dio_err_should_log(ngx_log_t \*log, ssize_t n)'; then
    echo "FAIL: line $SIG_LINE in $SRC is not" \
        "ngx_http_zstd_static_dio_err_should_log's signature" >&2
    exit 1
fi

# First "^}" at column 0 after START_LINE closes the function.
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
END_LINE=$((START_LINE + REL_END - 1))

# Also pull the two file-scope static counters and the window constant that
# the function reads/writes, plus the header comment block above them, so
# the extraction stays self-contained and does not require hand-copying
# state declarations that could drift from the shipped names.
WINDOW_LINE="$(grep -n '^#define NGX_HTTP_ZSTD_STATIC_DIO_ERR_WINDOW' "$SRC" | head -1 | cut -d: -f1)"
STATE_START="$(grep -n '^static time_t      ngx_http_zstd_static_dio_err_window_start;' "$SRC" | head -1 | cut -d: -f1)"
STATE_END="$(grep -n '^static ngx_uint_t  ngx_http_zstd_static_dio_err_suppressed;' "$SRC" | head -1 | cut -d: -f1)"

if [ -z "$WINDOW_LINE" ] || [ -z "$STATE_START" ] || [ -z "$STATE_END" ]; then
    echo "FAIL: could not locate the dio-err rate limiter's state declarations in $SRC" >&2
    exit 1
fi

mkdir -p "$OUT"
{
    echo "/* Generated by test_dio_err_ratelimit_unit.sh — verbatim"
    echo " * extraction from $SRC. Do not edit; re-run to regenerate. */"
    sed -n "${WINDOW_LINE}p" "$SRC"
    echo
    sed -n "${STATE_START},${STATE_END}p" "$SRC"
    echo
    sed -n "${START_LINE},${END_LINE}p" "$SRC"
} >"$OUT/generated_dio_ratelimit.inc"

# Sanity: the extraction must contain the markers this test relies on, or a
# source reflow silently produced an empty/garbage .inc.
if ! grep -q 'ngx_http_zstd_static_dio_err_should_log(ngx_log_t \*log, ssize_t n)' \
    "$OUT/generated_dio_ratelimit.inc"; then
    echo "FAIL: extracted fragment does not contain the function signature" >&2
    cat "$OUT/generated_dio_ratelimit.inc" >&2
    exit 1
fi
if ! grep -q 'NGX_HTTP_ZSTD_STATIC_DIO_ERR_WINDOW' "$OUT/generated_dio_ratelimit.inc"; then
    echo "FAIL: extracted fragment missing the window constant — extraction range wrong" >&2
    exit 1
fi

# The call site must not describe a successful short read as an alignment or
# device failure. Parse the sibling branches so moving the limiter call into
# the n >= 0 arm (or the malformed diagnostic into the hard-error arm) fails.
python3 - "$SRC" <<'PYEOF'
import sys

text = open(sys.argv[1], encoding="utf-8").read()
anchor = text.index("ngx_uint_t  dio_suppressed;")
start = text.index("if (n >= 0) {", anchor)

def block_at(pos):
    opening = text.index("{", pos)
    depth = 0
    for i in range(opening, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[opening + 1:i], i + 1
    raise ValueError("unterminated call-site branch")

short_read, after = block_at(start)
else_pos = text.index("else {", after)
hard_error, _ = block_at(else_pos)

malformed = "frame header -- treating sidecar as "
limiter = "ngx_http_zstd_static_dio_err_should_log(log, n);"
alignment = "aligned probe "
if malformed not in short_read or limiter in short_read or alignment in short_read:
    raise SystemExit("FAIL: n >= 0 branch is not malformed-only")
if limiter not in hard_error or alignment not in hard_error or malformed in hard_error:
    raise SystemExit("FAIL: n < 0 branch is not the rate-limited alignment error")
PYEOF

cp ci/tools/test_dio_err_ratelimit_unit.c "$OUT/test_dio_err_ratelimit_unit.c"

# -Wextra omitted deliberately: with ngx_log_debug1() stubbed as a no-op
# (matching its real non-NGX_DEBUG compiled shape), the `log` parameter
# goes genuinely unused in THIS build only — the same nginx calling-
# convention exemption already applied to the module's other unit
# fixtures and the repo's -Wextra lint policy.
"$CC" -Wall -Werror -O1 -g -I"$OUT" \
    -o "$OUT/dio_ratelimit_unit" "$OUT/test_dio_err_ratelimit_unit.c"
"$OUT/dio_ratelimit_unit"

echo "OK: directio probe log rate limiter unit fixture" \
    "(extracted from current $SRC)"
